### ISSUE TITLE
Разделение ответственности меню и пункта меню

### ISSUE THREAD

**Issue by Sussia** [vovkka/Todolist#4]
Есть список операций:
```python
class Operation(enum.Enum):
	addTask = 1
	viewTask = 2
	viewListOfTasks = 3
	deleteTask = 4
	exit = 5
```
Есть вывод меню:
```python
class Menu:
	def print_menu():
		print("\n1.Создать задачу")
		...
```
У нас операции соотносятся с принтом в меню, логично перенести все, что относится к операции (номер, название) в операцию, а в меню создать ~список~ массив используемых операций и в принте выводить их. 

Оперейшн будет примерно таким (для `match case` нужен питон >= 3.10 версии, либо поставить такой, либо тогда переписать на `if/else`):
```python
class Operation(enum.Enum):
    addTask = 1
    viewTask = 2

    def __str__(self):
        title = ""
        match self:
            case Operation.addTask:
                title = 'Создать задачу'
            case Operation.viewTask:
                title = 'Посмотреть задачу'
            case _:
                title = ''
        return f'{self.value}. {title}'
```
В меню будет что-то вроде:
```python
class Menu:
    options = [Operation.addTask, Operation.viewTask]

    def printMenu(self):
        for option in self.options:
            print(str(option))
```
Используется меню вот так:
```python
myMenu = Menu()
myMenu.printMenu()
```
Либо можно сразу сделать, чтобы пункты меню передавались в инициализатор меню, чтобы потом можно было допустим просто добавить строчку в инициализатор.

**Comment by vovkka** [comment]
def __str__(self):
        title = ""
        match self:
            case Operation.addTask:
                title = 'Создать задачу'
            case Operation.viewTask:
                title = 'Посмотреть задачу'
            case _:
                title = ''
        return f'{self.value}. {title}'
Как я понял match case используется, чтобы проверить, что значение соответствует какому-то типу данных и какому-то значению. А тут ты сравниваешь соответствует ли self чему то. Но ведь self это не обычный аргумент, а ключевое слово, которое позволяет ссылаться на атрибуты класса внутри самого класса, а тут ты его как просто переменную используешь.

**Comment by Sussia** [comment]
Не совсем понимаю, что тебя смущает
Self это указатель на объект, как любая другая переменная
Тут я проверяю для какой операции (по сути какое значение записано в self) был вызван `str` и возвращаю конкретную строчку

**Comment by vovkka** [comment]
Я понял, что я не до конца понимаю, что такое self и прочитал вот [это](https://www.programiz.com/article/python-self-why) и до меня доперло, что self передает сам объект класса. Я думал, что это просто какая-то магическая хреновина, которая ничего не передает))
