### ISSUE TITLE
Обновить метод для создания задачи: улчшить читабельность

### ISSUE THREAD

**Issue by Sussia** [vovkka/Todolist#5]
```python
task = Task(input("Введите заголовок задачи: "), input("Введите задачу: "), input("Введите дату дедлайна: "), [])
```
Это ты конечно экономично придумал, но строчки у нас бесплатные, можешь не стесняться)
```python
title = input("Введите заголовок задачи: ")
description = input("Введите задачу: ")
date = input("Введите дату дедлайна: ")
tags = ...

task = Task(title, description, date, tags)
self.tasks.append(task)
```
Так понятнее какой инпут за что отвечает, они не сбиты в кучу, появляется возможность отдельно для каждого поля какие-то манипуляции (см #6 ) проводить перед созданием самого объекта

**Comment by Sussia** [comment]
А че ты закрыл? Где пр?

**Comment by vovkka** [comment]
Ну вот это к тому же относится, что я тебе в вк написал. Я уже это сделал, но мне же не делать из-за этого пул реквест
